version: '3.9'
services:
  api:
    build:
      context: ./api
    image: wa-api:latest
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./api:/app
    command: node server.js
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    command: sh -c "corepack enable && corepack prepare pnpm@9.0.0 --activate && pnpm install && pnpm --filter @polyglot/web run dev"
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    depends_on:
      - api
