services:
  - type: web
    name: polyglot-api
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: api
    buildCommand: npm install --omit=dev
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
